# Generated by Django 4.2.18 on 2025-01-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_professor_semester_class_teachingassistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingassistant',
            name='points_awarded',
            field=models.IntegerField(default=5, editable=False),
        ),
    ]
