# Generated by Django 5.2.5 on 2025-09-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin Status'),
        ),
    ]
