# Generated by Django 4.2.18 on 2025-10-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='a_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='A Number'),
        ),
    ]
