# Generated by Django 4.2.18 on 2025-10-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_adminuser_delete_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['organization', 'name'], 'verbose_name': 'Event Type', 'verbose_name_plural': 'Event Types'},
        ),
        migrations.AddField(
            model_name='eventtype',
            name='function',
            field=models.CharField(default='General Event', help_text='Function or purpose of this event type', max_length=200),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='organization',
            field=models.CharField(choices=[('ASC', 'ASC'), ('PyData', 'PyData'), ('SOC', 'SOC'), ('Sports Analytics', 'Sports Analytics'), ('Marketing Analytics', 'Marketing Analytics'), ('DAISSA', 'DAISSA'), ('Baddies of Tech', 'Baddies of Tech')], default='ASC', help_text='Organization responsible for this event type', max_length=50),
        ),
    ]
