# Generated by Django 4.2.18 on 2025-10-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_eventtype_options_eventtype_function_and_more'),
    ]

    operations = [
    ]
