# Generated by Django 4.2.18 on 2025-10-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20251019_2123'),
    ]

    operations = [
    ]
