# Generated by Django 4.2.18 on 2025-10-19 21:27

from django.db import migrations, models


def populate_event_type(apps, schema_editor):
    """Populate event_type field with current function values."""
    Event = apps.get_model('api', 'Event')
    
    # Update all events to set event_type = function
    for event in Event.objects.all():
        Event.objects.filter(id=event.id).update(event_type=event.function)


def reverse_populate_event_type(apps, schema_editor):
    """Reverse migration - clear event_type field."""
    Event = apps.get_model('api', 'Event')
    Event.objects.all().update(event_type='')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20251019_2123'),
    ]

    operations = [
        # Step 1: Add the event_type field
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(
                max_length=100,
                help_text="Type of the event",
                default='General'
            ),
        ),
        
        # Step 2: Populate event_type with function values
        migrations.RunPython(populate_event_type, reverse_populate_event_type),
    ]
