# Generated by Django 4.2.18 on 2025-10-21 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20251019_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='organization',
            field=models.CharField(default='System', help_text='Organization the admin belongs to', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(help_text='Role of the admin user', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(help_text='Type of the event', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='function',
            field=models.CharField(help_text='Function/purpose of the event', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.CharField(help_text='Organization hosting the event (must match an AdminUser role)', max_length=100),
        ),
    ]
