# Generated by Django 4.2.18 on 2025-10-21 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_adminuser_options_remove_adminuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='organization',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(default='Admin', help_text="Admin role (e.g., 'Super Admin', 'Event Manager', etc.)", max_length=100),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
