# Generated by Django 4.2.18 on 2025-10-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_adminuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, help_text='Username from the user account', max_length=150),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(help_text="Admin role (e.g., 'Super Admin', 'Event Manager', etc.)", max_length=100),
        ),
    ]
