# Generated by Django 4.2.18 on 2025-10-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_student_username_alter_adminuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='function',
        ),
    ]
