# Generated by Django 4.2.18 on 2025-10-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_function_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cached_total_points',
            new_name='cached_attendance_count',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_points_update',
            new_name='last_attendance_update',
        ),
        migrations.RemoveField(
            model_name='event',
            name='points',
        ),
    ]
