# Generated by Django 4.2.18 on 2025-10-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_cached_total_points_student_cached_attendance_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='a_number',
            field=models.CharField(blank=True, help_text='Student A-Number', max_length=20),
        ),
    ]
