# Generated by Django 4.2.18 on 2025-10-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_student_a_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='a_number',
        ),
    ]
