# Generated by Django 4.2.18 on 2025-10-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_a_number_from_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this event repeats regularly'),
        ),
    ]
