# Generated by Django 4.2.18 on 2025-10-29 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_recurring_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, help_text='The original event this is a recurring instance of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='api.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateTimeField(blank=True, help_text='When the recurring events should stop (optional)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly')], default='none', help_text='How often the event repeats', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
