# Generated by Django 4.2.18 on 2025-11-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_classes_professors_tas_semesters'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(help_text='Organization associated with this event', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizations', to='api.event')),
            ],
            options={
                'db_table': 'event_organizations',
                'unique_together': {('event', 'organization')},
            },
        ),
    ]
