# Generated by Django 4.2.18 on 2025-11-08 01:16

from django.db import migrations, models
import django.db.models.deletion


def migrate_organizations(apps, schema_editor):
    """Populate Organization table with existing organizations from AdminUser roles"""
    Organization = apps.get_model('api', 'Organization')
    AdminUser = apps.get_model('api', 'AdminUser')
    
    # Get all unique roles from AdminUser (excluding Faculty and Super Admin)
    unique_roles = AdminUser.objects.exclude(
        role__in=['Faculty', 'Super Admin']
    ).values_list('role', flat=True).distinct()
    
    # Create Organization entries for each unique role
    for role in unique_roles:
        if role:  # Skip empty roles
            Organization.objects.get_or_create(name=role)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_event_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Organization name (e.g., 'DAISSA', 'Innovation Lab', etc.)", max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=6)),
                ('year', models.IntegerField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('season', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points_awarded', models.IntegerField(default=5, editable=False)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'unique_together': {('student', 'class_assigned')},
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this event repeats regularly'),
        ),
        migrations.AddField(
            model_name='class',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('course_code', 'professor', 'semester')},
        ),
        migrations.RunPython(
            code=migrate_organizations,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
