# Generated by Django 4.2.18 on 2025-11-08 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_organization_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganization',
            name='organization',
            field=models.ForeignKey(help_text='Organization associated with this event', on_delete=django.db.models.deletion.CASCADE, related_name='event_organizations', to='api.organization'),
        ),
    ]
