# Generated by Django 4.2.18 on 2025-11-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_change_event_organization_to_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorganization',
            name='created_at',
        ),
    ]
