# Generated by Django 4.2.18 on 2025-11-08 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_created_at_from_event_organization'),
    ]

    operations = [
    ]
