# Generated by Django 4.2.18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_migrate_event_organization_data'),
    ]

    operations = [
        # Revert EventOrganization.organization from ForeignKey back to CharField
        migrations.AlterField(
            model_name='eventorganization',
            name='organization',
            field=models.CharField(
                help_text='Organization associated with this event',
                max_length=100
            ),
        ),
    ]
