# Generated by Django 4.2.18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_event_organization'),
    ]

    operations = [
        # Since the table is empty, we can safely recreate it
        # Step 1: Drop the old table
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS event_organizations",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Create new table with ForeignKey
        migrations.RunSQL(
            sql="""
            CREATE TABLE event_organizations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                event_id INTEGER NOT NULL,
                organization_id INTEGER NOT NULL,
                created_at DATETIME NOT NULL,
                UNIQUE(event_id, organization_id),
                FOREIGN KEY (event_id) REFERENCES api_event(id) ON DELETE CASCADE,
                FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
            )
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 3: Update the model state
        migrations.AlterField(
            model_name='eventorganization',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_organizations',
                to='api.organization',
                help_text='Organization associated with this event'
            ),
        ),
    ]
