# Generated by Django 4.2.18 on 2026-02-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_eventorganization_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
