# Generated by Django 4.2.18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_delete_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('event_date', models.CharField(blank=True, max_length=32)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('a_number', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_checkins', to='api.event')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_checkins', to='api.student')),
            ],
            options={
                'verbose_name_plural': 'Pending check-ins',
            },
        ),
    ]
