# Generated by Django 4.2.18 on 2026-02-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_delete_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.CharField(help_text='Organization hosting the event', max_length=100),
        ),
    ]
